save_loc: "./results/ddp"
seed: 1000


data:
    variables: ['U','V','T','Q']
    surface_variables: ['SP','t2m','V500','U500','T500','Z500','Q500']
    save_loc: '/glade/derecho/scratch/wchapman/STAGING/TOTAL_*'
    mean_path: '/glade/derecho/scratch/wchapman/STAGING/All_2010_staged.SLO.mean.nc'
    std_path: '/glade/derecho/scratch/wchapman/STAGING/All_2010_staged.SLO.std.nc'

trainer:
    mode: ddp
    train_batch_size: 4
    valid_batch_size: 4
    learning_rate: 1.0e-04
    weight_decay: 0.0
    start_epoch: 0
    epochs: 1000
    amp: False
    grad_accum_every: 1
    apply_grad_penalty: False
    grad_max_norm: 1.0
    thread_workers: 4
    stopping_patience: 50

model:
    image_height: 640
    patch_height: 64
    image_width: 1280
    patch_width: 64
    frames: 15
    frame_patch_size: 5
    channels: 4
    dim: 1024
    layers: 6
    dim_head: 1024
    mlp_dim: 1024
    heads: 8
    depth: 4
    use_codebook: False
    vq_codebook_dim: 128
    vq_codebook_size: 65536  # 2^16
    vq_entropy_loss_weight: 0.8
    vq_diversity_gamma: 1.0
    discr_layers: 4
    
pbs:
  script_name: "gwm"
  select: "select:1:ncpus=32:ngpus=4:mem=480GB"
  walltime: "12:00:00"
  account: "NAML0001"
  queue: "main"
  out_path: "{save_loc}/out"
  err_path: "{save_loc}/out"
  bash: "module load conda; conda activate holodec"
  num_workers: 4
